### ISSUE TITLE
Cannot reproduce StandardToken.inlined.bytes

### ISSUE THREAD

**Issue by suhabe** [runtimeverification/verified-smart-contracts#189]
I followed the directions in the [Solidity Source Code and Compiled EVM Bytecode](https://github.com/runtimeverification/verified-smart-contracts/tree/master/erc20/zeppelin#verification-artifacts
) section to try to reproduce the EVM bytecode for erc20/zeppelin/StandardToken.inlined.sol.

However, the bytecode in erc20/zeppelin/StandardToken.inlined.bytes is different than the bytecode that Remix is generating now. The verification seems to be failing on this latest Remix-generated bytecode. Specifically, there seems to be a code section at the beginning that is absent from erc20/zeppelin/StandardToken.inlined.bytes.

The screenshot below highlights this section that does not show up in StandardToken.inlined.bytes. How can I get Remix to generate the bytecode that would make the verification pass?

![image](https://user-images.githubusercontent.com/613706/53508978-b68d3880-3a6f-11e9-838c-674609bcbd10.png)

**Comment by daejunpark** [comment]
There are two bytes of bytecode, and you have to use the "runtime" bytecode for the verification.  The one you are looking at is the bytecode used to create an account, which has some more stuff in the beginning as you can see.

**Comment by suhabe** [comment]
Thank you. That worked!
