### ISSUE TITLE
 makfile problem

### ISSUE THREAD

**Issue by lionheartStark** [runtimeverification/verified-smart-contracts#284]
I want to reproduce the result of "uniswap", but makfile is wrong in two place：
1、cd /home/qy/gituse/new_gituse/verified-smart-contracts/uniswap/.build/evm-semantics \
	&& git fetch \
	&& git clean -fdx \
	&& git reset --hard 81bcba1a73188942fdc34979c59ee7be7253ece9 \
	&& make tangle-deps \
	&& make defn \
	&& /home/qy/gituse/new_gituse/verified-smart-contracts/uniswap/.build/k/k-distribution/target/release/k/bin/kompile -v --debug --backend java -I .build/defn/java -d .build/defn/java --main-module ETHEREUM-SIMULATION --syntax-module ETHEREUM-SIMULATION .build/defn/java/driver.k

however, There is no .build/defn 

2、make: Entering directory '/home/qy/gituse/new_gituse/verified-smart-contracts/uniswap'
/home/qy/gituse/new_gituse/verified-smart-contracts/uniswap/.build/k/k-distribution/target/release/k/bin/kprove -v --debug -d /home/qy/gituse/new_gituse/verified-smart-contracts/uniswap/.build/evm-semantics/.build/defn/java -m VERIFICATION --z3-impl-timeout 500 --shutdown-wait-time 5s  --deterministic-functions --no-exc-wrap --cache-func-optimized --no-alpha-renaming --format-failures --boundary-cells k,pc --log-cells k,output,statusCode,localMem,pc,gas,wordStack,callData,accounts,memoryUsed,#pc,#result   /home/qy/gituse/new_gituse/verified-smart-contracts/specs/uniswap/uniswap/addLiquidity-1-spec.k
com.beust.jcommander.ParameterException: "--shutdown-wait-time": couldn't convert "5s" to an integer

You don't even know how your program calls ? it should be "5", not "5s"

**Comment by lionheartStark** [comment]
@kemitchell

**Comment by lionheartStark** [comment]
@palmskog @pdaian

**Comment by lionheartStark** [comment]
@daejunpark Can you help me? thanks

**Comment by denis-bogdanas** [comment]
Thanks for report. We will fix the issues. Uniswap is not in our continuous integration loop, so the Makefile got outdated while some options changed in K.

**Comment by denis-bogdanas** [comment]
This PR fixes it: https://github.com/runtimeverification/verified-smart-contracts/pull/286
