### ISSUE TITLE
Should report on deposit contract be published on arXiv?

### ISSUE THREAD

**Issue by ethers** [runtimeverification/verified-smart-contracts#321]
Should https://github.com/runtimeverification/verified-smart-contracts/blob/master/deposit/deposit-formal-verification.pdf be published on arXiv?

**Comment by daejunpark** [comment]
An academic paper version will be presented in CAV 2020 (http://i-cav.org/2020/accepted-papers/), and the tech report has been published in IDEALS (UIUC version of arXiv): http://hdl.handle.net/2142/107129
