### ISSUE TITLE
Supported Solidity Versions?

### ISSUE THREAD

**Issue by stephensj2** [runtimeverification/verified-smart-contracts#327]
I was hoping to verify some erc20 contracts written in solidity 0.5.0 using your tool, but was unable to find information about what versions of Solidity are supported. I performed a few tests myself, that yielded some odd results. Namely, I upgraded the zeppelin StandardToken to so it could be compiled with the Solidity 0.5.0 compiler. I then replaced the code section in the ini file with the bin-runtime received from the compiler. When I run make test (after cleaning and making again), a counterexample is found for the balanceOf spec rather than it being verified. A gist of my changes can be found [here](https://gist.github.com/stephensj2/c1c3a8bb3b53024d3ce2d55e7cc94622).

I therefore have 2 questions:
1. What versions of the solidity language are supported by this project?
2. If Solidity 0.5.0 is supported, do additional changes need to be made to the ini file (for example maybe the variable positions must change)?

Thanks in advance!

**Comment by ehildenb** [comment]
We haven't maintained this repository in a while, so it's unlikely that just upgrading the Solidity compiler will work. The basic build mechanisms from INI files => K specifications should still work though. But at the very least you likely will need to check the storage slot information, and there may be other side-conditions you need to update.

BTW, if you want to verify an ERC20, you may try out our ERC20-specific verification tool instead: https://erc20.fireflyblockchain.com/

**Comment by stephensj2** [comment]
I see. I had expected that would be the case. Also, thanks for the additional resource, I'll check it out!
